project:
  type: website

website:
  navbar:
    right:
      - text: "home"
        href: https://nicholdav.info/
      - text: "about"
        href: https://nicholdav.info/about.html
      - text: "blog"
        href: https://blog.nicholdav.info/
      - icon: github
        href: https://github.com/NickleDave
      - icon: twitter
        href: https://bsky.app/profile/nicholdav.bsky.social
format:
  html:
    theme: simplex
    css: styles.css
