project:
  type: website

website:
  navbar:
    right:
      - text: "home"
        href: https://nicholdav.info/
      - text: "about"
        href: https://nicholdav.info/about.html
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



